apiVersion: nifi.konpyutaika.com/v1
kind: NifiUser
metadata:
  name: ihproduct
  namespace: dev
spec:
  # identity field is use to define the user identity on NiFi cluster side,
  #	it use full when the user's name doesn't suite with Kubernetes resource name.
  identity: ihproduct
  # Contains the reference to the NifiCluster with the one the registry client is linked.
  clusterRef:
    name: nifikop
    namespace: dev
  # Whether or not the the operator also include a Java keystore format (JKS) with you secret
  includeJKS: false
  # Whether or not a certificate will be created for this user.
  createCert: false