apiVersion: nifi.konpyutaika.com/v1
kind: NifiUserGroup
metadata:
  name: group-test
spec:
  # Contains the reference to the NifiCluster with the one the registry client is linked.
  clusterRef:
    name: nifikop
    namespace: dev
  # contains the list of reference to NifiUsers that are part to the group.
  usersRef:
    - name: ihproduct
      namespace: dev
  # defines the list of access policies that will be granted to the group.
