apiVersion: nifi.konpyutaika.com/v1
kind: NifiUserGroup
metadata:
  name: group-test
  namespace: dev
spec:
  # Contains the reference to the NifiCluster with the one the registry client is linked.
  clusterRef:
    name: nifikop
    namespace: dev
  # contains the list of reference to NifiUsers that are part to the group.
  usersRef:
    - name: ihproduct
      namespace: dev
    - name: nifikop.nifi3scdev
      namespace: dev
    - name: nifikop-controller
      namespace: dev
    - name: node-0-nifikop
      namespace: dev
  # defines the list of access policies that will be granted to the group.
  accessPolicies:
    # defines the kind of access policy, could be "global" or "component".
    - type: global
      action: read
      resource: /flow
    - type: component
      action: read
      resource: /data
      componentType: "process-groups"
      componentId: "8d8a51e0-019b-1000-ffff-ffffe807ac01"
    - type: component
      action: read
      resource: /provenance-data
      componentType: "process-groups"
      componentId: "8d8a51e0-019b-1000-ffff-ffffe807ac01"
    - type: component
      action: read
      resource: /policies
      componentType: "process-groups"
      componentId: "8d8a51e0-019b-1000-ffff-ffffe807ac01"
    - type: component
      action: read
      resource: /data-transfer
      componentType: "process-groups"
      componentId: "8d8a51e0-019b-1000-ffff-ffffe807ac01"
    - type: component
      action: read
      resource: /
      componentType: "process-groups"
      componentId: "8d8a51e0-019b-1000-ffff-ffffe807ac01"
    - type: global
      action: write
      resource: /site-to-site
    - type: global
      action: read
      resource: /site-to-site