apiVersion: nifi.konpyutaika.com/v1alpha1
kind: NifiRegistryClient
metadata:
  name: scai-dqu-registry
spec:
  clusterRef:
    name: nifikop
  description: "SCAI DQU NiFi Registry"
  uri: "https://nifi-registry.dev.svc.cluster.local:18443/ih-registry/"