apiVersion: nifi.konpyutaika.com/v1alpha1
kind: NifiRegistryClient
metadata:
  name: squidflow
spec:
  clusterRef:
    name: nifikop
    namespace: qa
  description: "Squidflow demo"
  uri: "https://nifi-registry.dev.svc.cluster.local:18443/"