parameters:
  - name: Cluster
    displayName: Cluster
    type: string
    default: SCAI-CIN-AKS-DQUS
    values:
      - SCAI-CIN-AKS-DQUS
      
  - name: freshInstallation
    displayName: Is it for a Fresh Installation?
    type: boolean
    default: false
    values:
      - true
      - false

  - name: namespace
    displayName: Which environment?
    type: string
    default: dev
    values:
      - dev
      - qa 
  
  - name: installCertManager
    displayName: Install CertManager
    type: boolean
    default: false
  - name: installNiFiKop
    displayName: Install NiFiKop
    type: boolean
    default: false
  # - name: installZookeeper
  #   displayName: Install Zookeeper
  #   type: boolean
  #   default: false
  - name: createCluster
    displayName: Create NiFiCluster
    type: boolean
    default: true
  - name: deleteCluster
    displayName: Delete NiFiCluster
    type: boolean
    default: false


variables:
  - name: Environment
    ${{ if eq( parameters.namespace, 'dev') }}:
      value: dev
    ${{ elseif eq( parameters.namespace, 'qa') }}:
      value: qa
  - name: vmImageName
    value: ubuntu-latest
  - name: dockerRegistryServiceConnection
    ${{ if and(eq( parameters.Cluster, 'SCAI-CIN-AKS-DQU'), eq( parameters.namespace, 'uat')) }}:
      value: c1c632d7-148b-41c8-942d-3e71b69260f4
  - name: imageRepository
    value: 'ih-nifi'
  - name: containerRegistry
    value: 'scaicinacrall.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: imagePullSecret
    value: docker-registry-creds
  - name: tag
    value: '$(Build.BuildId)'

pool:
    name: '3SC' 
    demands:
        - Agent.ComputerName -equals SCAI-CIN-VMADA-DQUS

stages:
- stage: certmanager
  displayName: Deploy CertManager 
  condition: ${{ eq(parameters.installCertManager, 'true') }}
  jobs:
  - job: deployCertManager
    timeoutInMinutes: 6          # cancel pipeline in case of any misconfig 
    displayName: 'Installing Helm and CertManager'
    steps:
      - task: Kubernetes@1
        displayName: Create CRDs
        condition: ${{ eq(parameters.freshInstallation, 'true') }} #eq(parameters.Cluster, true)
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '${{parameters.Cluster}}'
          command: 'apply'
          arguments: '-f https://github.com/jetstack/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml'
          forceUpdate: false

      # - task: HelmInstaller@1
      #   inputs:
          # helmVersionToInstall: 'latest'
      
      - script: |
          sudo apt-get install curl gpg apt-transport-https --yes
          curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y
          helm repo add jetstack https://charts.jetstack.io 
          helm repo update  
    
      - task: HelmDeploy@1
        displayName: cert-manager installation.
        condition: succeeded()
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: '${{parameters.Cluster}}'
          namespace: '$(Environment)'
          command: 'install'
          chartType: 'Name'
          chartName: 'jetstack/cert-manager'
          releaseName: 'cert-manager'
          arguments: '--version v1.17.2'

- stage: nifikop
  displayName: Deploy NiFiKop
  condition: ${{ eq(parameters.installNiFiKop, 'true') }}
  jobs:
  - job: installingNiFiKop
    displayName: 'Intalling NiFiKop'
    timeoutInMinutes: 2          # cancel pipeline in case of any misconfig 
    steps:
      # - task: HelmInstaller@1
      #   inputs:
      #     helmVersionToInstall: 'latest'

      - script: |
          sudo apt-get install curl gpg apt-transport-https --yes
          curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y
      
      - task: HelmDeploy@1
        displayName: 'Install NifiKop'
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: '${{parameters.Cluster}}'
          command: 'install'
          chartType: 'Name'
          chartName: 'oci://ghcr.io/konpyutaika/helm-charts/nifikop'
          releaseName: 'nifikop'
          namespace: '$(Environment)'
          arguments: '--version 1.14.2 --set image.tag=v1.14.2-release --set resources.requests.memory=256Mi --set resources.requests.cpu=250m --set resources.limits.memory=256Mi --set resources.limits.cpu=250m --set namespaces={$(Environment)}'

# - stage: zookeeper 
  # displayName: Deploy Zookeeper
  # condition: ${{ eq(parameters.installZookeeper, 'true') }}
  # jobs:
  # - job: installZookeeper
  #   displayName: 'Installing Helm and Zookeeper'
  #   timeoutInMinutes: 6          
  #   steps:
  #     - task: HelmInstaller@1
  #       inputs:
  #         helmVersionToInstall: 'latest'
      
  #     - script: |
  #         helm repo add bitnami https://charts.bitnami.com/bitnami 
  #         helm repo update  

  #     - task: HelmDeploy@1
  #       displayName: 'Install Zookeeper'
  #       inputs:
  #         connectionType: 'Kubernetes Service Connection'
  #         kubernetesServiceConnection: '${{parameters.Cluster}}'
  #         command: 'install'
  #         releaseName: 'nifizkp-zookeeper'
  #         namespace: '$(Environment)'
  #         chartType: 'Name'
  #         chartName: 'bitnami/zookeeper'
  #         arguments: '--set replicaCount=1 --set auth.enabled=false --set service.type=ClusterIP --set service.headless.clusterIP=None --set persistence.enabled=true --set persistence.size=5Gi --set volumePermissions.enabled=true'

- stage: nificluster
  displayName: Deploying NiFiCluster
  condition: ${{ eq(parameters.createCluster, 'true') }}
  jobs:
  - deployment:
    displayName: Deploying NiFiCluster 
    # pool:
    #   vmImage: $(vmImageName)
    environment: $(Environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - checkout: self

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              kubernetesServiceConnection: '${{parameters.Cluster}}'
              namespace: $(Environment)
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: Building Docker Image
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)-$(Environment)'
              command: 'build'
              Dockerfile: '$(dockerfilePath)'
              tags: '$(tag)'
              arguments: '--no-cache'

          - task: Docker@2
            displayName: Pushing Docker Image To ACR
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)-$(Environment)'
              command: 'push'
              tags: '$(tag)'

          - script: |
              echo "Performing image tag substitution in manifest file..."
              FULL_IMAGE_NAME="$(containerRegistry)/$(imageRepository)-$(Environment):$(tag)"
              echo "${FULL_IMAGE_NAME}"
              sed -i "s|buildid|$(Build.BuildId)|g" $(Build.SourcesDirectory)/deployments/nificluster-$(Environment).yaml
              echo "Substitution complete."
              echo "--- Start of Updated Manifest File ---"
              cat $(Build.SourcesDirectory)/deployments/nificluster-$(Environment).yaml
              echo "--- End of Updated Manifest File ---"
            displayName: 'Update Manifest File'

          - task: KubernetesManifest@1
            displayName: Deploy NiFiCluster to Kubernetes
            inputs:
              kubernetesServiceConnection: '${{parameters.Cluster}}'
              namespace: $(Environment)
              action: deploy
              imagePullSecrets: |
                $(imagePullSecret)
              manifests: |
                $(Build.SourcesDirectory)/deployments/nificluster-$(Environment).yaml
          
          - task: KubernetesManifest@1
            displayName: Deploy ConfigMap to Kubernetes
            inputs:
              kubernetesServiceConnection: '${{parameters.Cluster}}'
              namespace: $(Environment)
              action: deploy
              manifests: |
                $(Build.SourcesDirectory)/deployments/config-$(Environment).yaml
          
          - task: KubernetesManifest@1 
            displayName: Deploy NginxProxy to Kubernetes
            inputs:
              kubernetesServiceConnection: '${{parameters.Cluster}}'
              namespace: $(Environment)
              action: deploy
              manifests: |
                $(Build.SourcesDirectory)/deployments/deployment-nginx-$(Environment).yaml

- stage: deletenificluster
  displayName: Delete NiFiCluster
  condition: ${{ eq(parameters.deleteCluster, 'true') }}
  jobs:
  - deployment:
    displayName: Deleting NiFiCluster 
    environment: $(Environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubernetesManifest@1
            displayName: Delete existing NiFiCluster
            inputs:
              kubernetesServiceConnection: '${{parameters.Cluster}}'
              namespace: $(Environment)
              action: delete
              arguments: -f $(Build.SourcesDirectory)/deployments/nificluster-$(Environment).yaml
            continueOnError: true